project:
  type: website

website:
  title: "JinsBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Jiniverse
      - icon: twitter
        href: https://twitter.com/JinMountain
format:
  html:
    theme: minty
    css: styles.css

comments:
  giscus:
    repo: Jiniverse/MyBlog

